name: demo_rampup_py395
channels:
  - conda-forge
  - defaults
dependencies:
  - pip:
    - anndata==0.7.5
    - biopython==1.78
    - cellpose==0.6.1
    - et-xmlfile==1.0.1
    - get-version==2.1
    - harmonypy==0.0.5
    - legacy-api-wrap==1.2
    - natsort==7.1.0
    - opencv-python-headless==4.5.1.48
    - openpyxl==3.0.7
    - psutil==5.8.0
    - pyfftw==0.12.0
    - scanpy==1.6.1
    - setuptools-scm==5.0.1
    - sinfo==0.3.1
    - stdlib-list==0.8.0
    - torch==1.7.1
    - tqdm==4.56.0
    - umap-learn==0.4.6