name: data_analysis_py39
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip=21
  - pip:
      - scikit-learn==1.1.2
      - pandas==1.4
      - numpy==1.22
      - matplotlib==3.4
      - seaborn==0.11
      - statsmodels==0.13.0

    